services:
  mynginx:
    #container_name: nginx-container
    image: nginx
    ports: 
      - ":80"
    volumes:
      - datavol1:/v1
      - datavol2:/v2
    networks:
      - mynetwork-1
 
  myapache:
    container_name: apache-container
    image: php:8.0-apache
    ports:
    - ":80"
    volumes:
      - datavol1:/v1
      - datavol2:/v2
    networks:
      - mynetwork-1
 
volumes:
  datavol1:
    name: datavol1
  datavol2:
    name: datavol2
 
networks:
  mynetwork-1:
    name: mynetwork1
    driver: bridge